export const GET_LOGGIN = "GET_LOGGIN";
export const FAILED_GET_LOGGIN = "FAILED_GET_LOGGIN";

export const GET_LABEL = "GET_LABEL";
export const FAILED_GET_LABEL = "FAILED_GET_LABEL";

export const STYLE_COMPONENTS = "STYLE_COMPONENTS";
export const GRID_COMPONENTS = "GRID_COMPONENTS";
export const DARKMODE_COMPONENTS = "DARKMODE_COMPONENTS";
export const MENU_COMPONENTS = "MENU_COMPONENTS";
export const SLIDETASK_COMPONENTS = "SLIDETASK_COMPONENTS";

export const GET_TASK = "GET_TASK";
export const FAILED_GET_TASK = "FAILED_GET_TASK";
