export const GET_LOGGIN = "GET_LOGGIN";
export const FAILED_GET_LOGGIN = "FAILED_GET_LOGGIN";
export const GET_REGISTER = "GET_REGISTER";
export const FAILED_REGISTER = "FAILED_REGISTER";
export const MESSAGE_REGISTER = "MESSAGE_REGISTER";
export const GET_DATA_USERS = "GET_DATA_USERS";
export const REMOVE_DATA_USERS = "REMOVE_DATA_USERS";
export const FAILED_GET_DATA_USERS = "FAILED_GET_DATA_USERS";
export const IS_LOGGIN = "IS_LOGIN";

export const START_FORGOT_PASSWORD = "START_FORGOT_PASSWORD";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FAILED_FORGOT_PASSWORD = "FAILED_FORGOT_PASSWORD";

export const START_RESET_PASSWORD = "START_RESET_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const FAILED_RESET_PASSWORD = "FAILED_RESET_PASSWORD";
export const INVALIDE_SIGNATURE_RESET_PASSWORD =
  "INVALIDE_SIGNATURE_RESET_PASSWORD";

export const GET_LABEL = "GET_LABEL";
export const FAILED_GET_LABEL = "FAILED_GET_LABEL";
export const ADD_LABEL = "ADD_LABEL";
export const FAILED_ADD_LABEL = "FAILED_ADD_LABEL";
export const REMOVE_MESSAGE_ADD_LABEL = "REMOVE_MESSAGE_ADD_LABEL";

export const GET_TASK_BY_ARCHIVE = "GET_TASK_BY_ARCHIVE";
export const MESSAGE_GET_TASK_BY_ARCHIVE = "MESSAGE_GET_TASK_BY_ARCHIVE";

export const STYLE_COMPONENTS = "STYLE_COMPONENTS";
export const GRID_COMPONENTS = "GRID_COMPONENTS";
export const CALENDER_COMPONENTS = "CALENDER_COMPONENTS";
export const DARKMODE_ON_COMPONENTS = "DARKMODE_ON_COMPONENTS";
export const DARKMODE_OFF_COMPONENTS = "DARKMODE_OFF_COMPONENTS";
export const MENU_COMPONENTS = "MENU_COMPONENTS";
export const SLIDETASK_COMPONENTS = "SLIDETASK_COMPONENTS";
export const SEARCH_TERM = "SEARCH_TERM";
export const REMOVE_VALUE_SEARCH_TERM = "REMOVE_VALUE_SEARCH_TERM";
export const SLIDE_DETAIL = "SLIDE_DETAIL";
export const SLIDE_OOF_DETAIL = "SLIDE_OOF_DETAIL";
export const MODAL_DELETE_ON = "MODAL_DELETE_ON ";
export const MODAL_DELETE_OFF = "MODAL_DELETE_OFF ";

export const GET_TASK = "GET_TASK";
export const FAILED_GET_TASK = "FAILED_GET_TASK";
export const ADD_TASK = "ADD_TASK";
export const FAILED_ADD_TASK = "FAILED_ADD_TASK";
export const REMOVE_DATA_IN_ADD_TASK = "REMOVE_DATA_IN_ADD_TASK";
export const GET_TASK_BY_LABEL = "GET_TASK_BY_LABEL";
export const NO_DATA_IN_TASK_BY_LABEL = "NO_DATA_IN_TASK_BY_LABEL";
export const GET_DETAIL_TASK = "GET_DETAIL_TASK";
export const REMOVE_DETAIL_TASK = "REMOVE_DETAIL_TASK";
export const REMOVE_DELETE_TASK = "REMOVE_DELETE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const FAILED_DELETE_TASK = "FAILED_DELETE_TASK";

export const PINS_TASK = "PINS_TASK";
export const REMOVE_MESSAGE_PINS_TASK = "REMOVE_MESSAGE_PINS_TASK";
export const FAILED_PINS_TASK = "FAILED_PINS_TASK";

export const ARCHIVE_TASK = "ARCHIVE_TASK";
export const REMOVE_MESSAGE_ARCHIVE_TASK = "REMOVE_MESSAGE_ARCHIVE_TASK";
export const FAILED_ARCHIVE_TASK = "FAILED_ARCHIVE_TASK";
