export const GET_LOGGIN = "GET_LOGGIN";
export const FAILED_GET_LOGGIN = "FAILED_GET_LOGGIN";
export const GET_DATA_USERS = "GET_DATA_USERS";
export const FAILED_GET_DATA_USERS = "FAILED_GET_DATA_USERS";

export const GET_LABEL = "GET_LABEL";
export const FAILED_GET_LABEL = "FAILED_GET_LABEL";
export const ADD_LABEL = "ADD_LABEL";
export const FAILED_ADD_LABEL = "FAILED_ADD_LABEL";
export const REMOVE_MESSAGE_ADD_LABEL = "REMOVE_MESSAGE_ADD_LABEL";

export const STYLE_COMPONENTS = "STYLE_COMPONENTS";
export const GRID_COMPONENTS = "GRID_COMPONENTS";
export const CALENDER_COMPONENTS = "CALENDER_COMPONENTS";
export const DARKMODE_ON_COMPONENTS = "DARKMODE_ON_COMPONENTS";
export const DARKMODE_OFF_COMPONENTS = "DARKMODE_OFF_COMPONENTS";
export const MENU_COMPONENTS = "MENU_COMPONENTS";
export const SLIDETASK_COMPONENTS = "SLIDETASK_COMPONENTS";
export const SEARCH_TERM = "SEARCH_TERM";
export const REMOVE_VALUE_SEARCH_TERM = "REMOVE_VALUE_SEARCH_TERM";
export const SLIDE_DETAIL = "SLIDE_DETAIL";

export const GET_TASK = "GET_TASK";
export const FAILED_GET_TASK = "FAILED_GET_TASK";
export const ADD_TASK = "ADD_TASK";
export const FAILED_ADD_TASK = "FAILED_ADD_TASK";
export const REMOVE_DATA_IN_ADD_TASK = "REMOVE_DATA_IN_ADD_TASK";
export const GET_TASK_BY_LABEL = "GET_TASK_BY_LABEL";
export const NO_DATA_IN_TASK_BY_LABEL = "NO_DATA_IN_TASK_BY_LABEL";
export const GET_DETAIL_TASK = "GET_DETAIL_TASK";
export const REMOVE_DETAIL_TASK = "REMOVE_DETAIL_TASK";
